### ISSUE TITLE
compile the project faile.

### ISSUE THREAD

**Issue by cuipingxu** [z0nt/pstack#1]
elfinfo.h:41: error: 'Elf_Addr' does not name a type
elfinfo.h:45: error: ISO C++ forbids declaration of 'Elf_Ehdr' with no type
elfinfo.h:45: error: expected ';' before '_' token
elfinfo.h:46: error: ISO C++ forbids declaration of 'Elf_Phdr' with no type
elfinfo.h:46: error: expected ';' before '_' token
elfinfo.h:47: error: ISO C++ forbids declaration of 'Elf_Shdr' with no type

---

whether loss some *.h file ?

**Comment by z0nt** [comment]
What version of FreeBSD are you using?

**Comment by cuipingxu** [comment]
Is it work fine in Linux,  Machine is below,

Linux version 2.6.16.46-0.12-xenpae-1024-18 (geeko@buildhost) (gcc version 4.1.0 (SUSE Linux)) #31 SMP Wed Oct 24 21:10:58 CST 2007

**Comment by z0nt** [comment]
This pstack is for FreeBSD not for Linux.
